name: Laravel

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    laravel-tests:
        runs-on: ubuntu-latest
        env:
            DB_CONNECTION: mysql
            DB_HOST: localhost
            DB_DATABASE: testdb
            DB_USERNAME: root
            DB_PASSWORD: root
        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.1"
            - name: Set up Mysql
              run: |
                  sudo systemctl start mysql
                  mysql -e 'CREATE DATABASE testdb;' -uroot -proot
                  mysql -e 'SHOW DATABASES;' -uroot -proot

            - uses: actions/checkout@v4
            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"
            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
                  npm install && npm run build
            - name: Generate key
              run: php artisan key:generate
            - name: Directory Permissions
              run: chmod -R 777 storage bootstrap/cache
            - name: Execute tests (Unit and Feature tests) via PHPUnit
              run: vendor/bin/phpunit
